### PR TITLE
Initial requirements.txt

### PR DESCRIPTION
**Pull request by sethfitz**
This isn't quite ready for primetime--I don't know what the correct version string for `pyopencv` is. Do you?

### CODE REVIEW

**Comment by dakotabenjamin** [comment]
I do not know either.

**Comment by dakotabenjamin** [comment]
I'm considering just saying you need to install opencv yourself by running `sudo apt-get install python-opencv`

**Comment by sethfitz** [comment]
Works for me. Not an option on OS X (where it would be nice to be able to run this within a virtualenv), but then people can spend more time figuring out how to install it.

**Comment by dakotabenjamin** [comment]
See install instructions in  readme

**Pull request closed without merging**
